# Generated by Django 4.1.3 on 2022-11-14 16:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_course_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='date',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='added_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
