# Generated by Django 4.1.3 on 2022-11-15 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_remove_enrollment_date_enrollment_added_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='course',
            new_name='courses',
        ),
        migrations.AddField(
            model_name='course',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
